### ISSUE TITLE
Django backend init

### ISSUE THREAD

**Issue by EwanMe** [EwanMe/IMDb_episode_ratings#15]

**Comment by TolulopeJoel** [comment]
Hey Hallvard! This sounds cool

I would like to work on the Django backend

**Comment by EwanMe** [comment]
Hi [TolulopeJoel](https://github.com/TolulopeJoel)! I'm very grateful for your interest in my project. Unfortunately I am not able to accept PR's at this time, since this is a small personal project that I work on in irregularly. Sorry for the inconvenience!

**Comment by TolulopeJoel** [comment]
I understand. No problem man.
Reach out to me when you are ready to work on this or any other future projects 😉

**Comment by TolulopeJoel** [comment]
> Hi [TolulopeJoel](https://github.com/TolulopeJoel)! I'm very grateful for your interest in my project. Unfortunately I am not able to accept PR's at this time, since this is a small personal project that I work on in irregularly. Sorry for the inconvenience!

I understand. No problem man.
Reach out to me when you are ready to work on this or any other future projects 😉
